### ISSUE TITLE
Error: Unknown version detected

### ISSUE THREAD

**Issue by QSlotus** [Hiro420/FetchHotfix#1]
I installed the dependencies using `npm i` as per the readme, but when I run `npm run start "E:\Program Files\Star Rail\Game"` I get an error.
Here is the error message：
```
PS E:\桌面\Github Files\FetchHotfix> npm i

added 29 packages in 2s

1 package is looking for funding
  run `npm fund` for details
PS E:\桌面\Github Files\FetchHotfix> npm run start "E:\Program Files\Star Rail\Game"

> gethotupdate@1.0.0 start
> ts-node fetch.ts E:\Program Files\Star Rail\Game

Dispatch Seed: cd3cd8494d
Version: CNPRODWin2.2.0
Build: CnLive
E:\桌面\Github Files\FetchHotfix\fetch.ts:4
import { decode, simplify } from "./decoder";
           ^
Error: Unknown version detected
    at E:\桌面\Github Files\FetchHotfix\fetch.ts:95:19
    at Generator.next (<anonymous>)
    at E:\桌面\Github Files\FetchHotfix\fetch.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\桌面\Github Files\FetchHotfix\fetch.ts:4:12)
    at main (E:\桌面\Github Files\FetchHotfix\fetch.ts:42:12)
    at Object.<anonymous> (E:\桌面\Github Files\FetchHotfix\fetch.ts:128:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module.m._compile (E:\桌面\Github Files\FetchHotfix\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
PS E:\桌面\Github Files\FetchHotfix>
```

**Comment by Hiro420** [comment]
fixed with latest update
